Repository capstoneDesign-taxiCarpool/team_BE, pull requests merged in 2025-04, with the labels that each got.

#15 Refactor merge conflict
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/auth/AuthController.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/auth/AuthService.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/auth/SignUpDTO.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/member/MemberController.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/member/MemberService.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/member/dto/MemberCreateDTO.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/member/dto/MemberResponseDTO.java
  taxi-carpool/src/test/java/edu/kangwon/university/taxicarpool/member/MemberControllerTest.java
  taxi-carpool/src/test/java/edu/kangwon/university/taxicarpool/member/MemberServiceTest.java
Labels: enhancement, refactor

#18 [#17] feat: 키워드로 주변 장소 검색 기능 추가
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/exception/GlobalExceptionHandler.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/map/MapConfig.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/map/MapController.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/map/MapPlaceDTO.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/map/MapSearchResponseDTO.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/map/MapService.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/map/exception/KakaoApiParseException.java
  taxi-carpool/src/main/resources/application.properties
Labels: enhancement

#31 Feature improve validation error handling
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/exception/GlobalExceptionHandler.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/member/validation/EmailValidator.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/member/validation/NicknameValidator.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/member/validation/PasswordValidator.java
Labels: bug, enhancement

#34 [#32, 33] 컨트롤러의 validation, partyDelete오류 수정
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/auth/AuthService.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/auth/LoginDTO.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/auth/LogoutDTO.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/exception/GlobalExceptionHandler.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/party/PartyController.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/party/PartyDTO.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/party/PartyRepository.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/party/PartyService.java
Labels: bug

#44 [#43] config에 토큰 인증 없이 허용가능한 경로 추가
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/auth/SecurityConfig.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/init/DataInitializer.java
  taxi-carpool/src/main/java/edu/kangwon/university/taxicarpool/party/PartyDTO.java
Labels: bug

#64 fix(deploy): 워크플로우 실행 시 ec2에 환경변수가 전달되지 않는 버그 수정
  .github/workflows/main.yml
Labels: bug
